name: release please

on:
  workflow_call:
    inputs:
      project_path:
        description: 'project path'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
