name: Service2-ReleasePlease

on:
  push:
    branches:
      - main
    paths:
      - "web/apps/service2/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'web/apps/service2'
      - name: deploy
        needs: release
        if: ${{ steps.release.outputs['web/apps/service2--release_created'] }}
        run:
          echo "deploy"

