name: Service1-ReleasePlease

on:
  push:
    branches:
      - main
    paths:
      - "web/apps/service1/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "web/apps/service1"
          release-type: simple
          config-file: default
          manifest-file: default
      - name: deploy
        if: ${{ steps.release.outputs['web/apps/service--release_created'] }}
        run:
          echo "deploy"

